apiVersion: v1
kind: Pod
metadata:
  name: custom-pod
  labels:
    app: demo
    environment: testing
    team: devops
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
